//tag::ref-doc[]
= Cassandra Sink

This sink application writes the content of each message it receives into Cassandra.

It expects a payload of JSON String and uses it's properties to map to table columns.

== Input

*Headers:*

 * `Content-Type: application/json`

*Payload:*

A JSON String or byte array representing the entity (or a list of entities) to be persisted

== Output

 N/A

== Options

The **$$cassandra$$** $$sink$$ has the following options:

//tag::configuration-properties[]
$$cassandra.async$$:: $$Async mode for CassandraMessageHandler.$$ *($$Boolean$$, default: `$$true$$`)*
$$cassandra.cluster.create-keyspace$$:: $$Flag to create (or not) keyspace on application startup.$$ *($$Boolean$$, default: `$$false$$`)*
$$cassandra.cluster.entity-base-packages$$:: $$Base packages to scan for entities annotated with Table annotations.$$ *($$String[]$$, default: `$$[]$$`)*
$$cassandra.cluster.init-script$$:: $$Resource with CQL scripts (delimited by ';') to initialize keyspace schema.$$ *($$Resource$$, default: `$$<none>$$`)*
$$cassandra.cluster.metrics-enabled$$:: $$Enable/disable metrics collection for the created cluster.$$ *($$Boolean$$, default: `$$<none>$$`)*
$$cassandra.cluster.skip-ssl-validation$$:: $$Flag to validate the Servers' SSL certs$$ *($$Boolean$$, default: `$$false$$`)*
$$cassandra.consistency-level$$:: $$The consistency level for write operation.$$ *($$ConsistencyLevel$$, default: `$$<none>$$`, possible values: `ANY`,`ONE`,`TWO`,`THREE`,`QUORUM`,`ALL`,`LOCAL_QUORUM`,`EACH_QUORUM`,`SERIAL`,`LOCAL_SERIAL`,`LOCAL_ONE`)*
$$cassandra.ingest-query$$:: $$Ingest Cassandra query.$$ *($$String$$, default: `$$<none>$$`)*
$$cassandra.query-type$$:: $$QueryType for Cassandra Sink.$$ *($$Type$$, default: `$$<none>$$`, possible values: `INSERT`,`UPDATE`,`DELETE`,`STATEMENT`)*
$$cassandra.statement-expression$$:: $$Expression in Cassandra query DSL style.$$ *($$Expression$$, default: `$$<none>$$`)*
$$cassandra.ttl$$:: $$Time-to-live option of WriteOptions.$$ *($$Integer$$, default: `$$0$$`)*
$$spring.data.cassandra.cluster-name$$:: $$Name of the Cassandra cluster.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.data.cassandra.compression$$:: $$Compression supported by the Cassandra binary protocol.$$ *($$Compression$$, default: `$$none$$`, possible values: ``,`snappy`,`lz4`)*
$$spring.data.cassandra.connect-timeout$$:: $$Socket option: connection time out.$$ *($$Duration$$, default: `$$<none>$$`)*
$$spring.data.cassandra.consistency-level$$:: $$Queries consistency level.$$ *($$ConsistencyLevel$$, default: `$$<none>$$`, possible values: `ANY`,`ONE`,`TWO`,`THREE`,`QUORUM`,`ALL`,`LOCAL_QUORUM`,`EACH_QUORUM`,`SERIAL`,`LOCAL_SERIAL`,`LOCAL_ONE`)*
$$spring.data.cassandra.contact-points$$:: $$Cluster node addresses.$$ *($$List<String>$$, default: `$$[localhost]$$`)*
$$spring.data.cassandra.fetch-size$$:: $$Queries default fetch size.$$ *($$Integer$$, default: `$$<none>$$`)*
$$spring.data.cassandra.jmx-enabled$$:: $$Whether to enable JMX reporting. Default to false as Cassandra JMX reporting is not compatible with Dropwizard Metrics.$$ *($$Boolean$$, default: `$$false$$`)*
$$spring.data.cassandra.keyspace-name$$:: $$Keyspace name to use.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.data.cassandra.load-balancing-policy$$:: $$Class name of the load balancing policy. The class must have a default constructor.$$ *($$Class<LoadBalancingPolicy>$$, default: `$$<none>$$`)*
$$spring.data.cassandra.password$$:: $$Login password of the server.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.data.cassandra.port$$:: $$Port of the Cassandra server.$$ *($$Integer$$, default: `$$<none>$$`)*
$$spring.data.cassandra.read-timeout$$:: $$Socket option: read time out.$$ *($$Duration$$, default: `$$<none>$$`)*
$$spring.data.cassandra.reconnection-policy$$:: $$Class name of the reconnection policy. The class must have a default constructor.$$ *($$Class<ReconnectionPolicy>$$, default: `$$<none>$$`)*
$$spring.data.cassandra.retry-policy$$:: $$Class name of the retry policy. The class must have a default constructor.$$ *($$Class<RetryPolicy>$$, default: `$$<none>$$`)*
$$spring.data.cassandra.schema-action$$:: $$Schema action to take at startup.$$ *($$String$$, default: `$$none$$`)*
$$spring.data.cassandra.serial-consistency-level$$:: $$Queries serial consistency level.$$ *($$ConsistencyLevel$$, default: `$$<none>$$`, possible values: `ANY`,`ONE`,`TWO`,`THREE`,`QUORUM`,`ALL`,`LOCAL_QUORUM`,`EACH_QUORUM`,`SERIAL`,`LOCAL_SERIAL`,`LOCAL_ONE`)*
$$spring.data.cassandra.ssl$$:: $$Enable SSL support.$$ *($$Boolean$$, default: `$$false$$`)*
$$spring.data.cassandra.username$$:: $$Login user of the server.$$ *($$String$$, default: `$$<none>$$`)*
//end::configuration-properties[]

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

The following example assumes a JSON payload is sent to a default destination called `input`, the sink parses some of its properties (id,time,customer_id,value) and persists them into a table called `orders`.

```
java -jar cassandra_sink.jar --cassandra.cluster.keyspace=test
--cassandra.ingest-query="insert into orders(id,time,customer_id, value) values (?,?,?,?)"
```

//end::ref-doc[]
