//tag::ref-doc[]
= Cassandra Sink

This sink application writes the content of each message it receives into Cassandra.

It expects a payload of JSON String and uses it's properties to map to table columns.

== Input

*Headers:*

 * `Content-Type: application/json`

*Payload:*

A JSON String or byte array representing the entity (or a list of entities) to be persisted

== Output

 N/A

== Options

The **$$cassandra$$** $$sink$$ has the following options:

//tag::configuration-properties[]
$$cassandra.cluster.compression-type$$:: $$The compression to use for the transport.$$ *($$CompressionType$$, default: `$$<none>$$`, possible values: `NONE`,`SNAPPY`,`LZ4`)*
$$cassandra.cluster.contact-points$$:: $$The comma-delimited string of the hosts to connect to Cassandra.$$ *($$String$$, default: `$$<none>$$`)*
$$cassandra.cluster.create-keyspace$$:: $$The flag to create (or not) keyspace on application startup.$$ *($$Boolean$$, default: `$$false$$`)*
$$cassandra.cluster.entity-base-packages$$:: $$The base packages to scan for entities annotated with Table annotations.$$ *($$String[]$$, default: `$$[]$$`)*
$$cassandra.cluster.init-script$$:: $$The resource with CQL scripts (delimited by ';') to initialize keyspace schema.$$ *($$Resource$$, default: `$$<none>$$`)*
$$cassandra.cluster.keyspace$$:: $$The keyspace name to connect to.$$ *($$String$$, default: `$$<none>$$`)*
$$cassandra.cluster.metrics-enabled$$:: $$Enable/disable metrics collection for the created cluster.$$ *($$Boolean$$, default: `$$<none>$$`)*
$$cassandra.cluster.password$$:: $$The password for connection.$$ *($$String$$, default: `$$<none>$$`)*
$$cassandra.cluster.port$$:: $$The port to use to connect to the Cassandra host.$$ *($$Integer$$, default: `$$<none>$$`)*
$$cassandra.cluster.schema-action$$:: $$The schema action to perform.$$ *($$SchemaAction$$, default: `$$<none>$$`, possible values: `NONE`,`CREATE`,`CREATE_IF_NOT_EXISTS`,`RECREATE`,`RECREATE_DROP_UNUSED`)*
$$cassandra.cluster.skip-ssl-validation$$:: $$The flag to validate the Servers' SSL certs$$ *($$Boolean$$, default: `$$false$$`)*
$$cassandra.cluster.use-ssl$$:: $$The flag to use SSL to connect$$ *($$Boolean$$, default: `$$false$$`)*
$$cassandra.cluster.username$$:: $$The username for connection.$$ *($$String$$, default: `$$<none>$$`)*
$$cassandra.consistency-level$$:: $$The consistencyLevel option of WriteOptions.$$ *($$ConsistencyLevel$$, default: `$$<none>$$`, possible values: `ANY`,`ONE`,`TWO`,`THREE`,`ALL`,`LOCAL_ONE`,`SERIAL`,`LOCAL_SERIAL`,`QUORUM`,`LOCAL_QUORUM`,`EACH_QUORUM`)*
$$cassandra.ingest-query$$:: $$The ingest Cassandra query.$$ *($$String$$, default: `$$<none>$$`)*
$$cassandra.query-type$$:: $$The queryType for Cassandra Sink.$$ *($$Type$$, default: `$$<none>$$`, possible values: `INSERT`,`UPDATE`,`DELETE`,`STATEMENT`)*
$$cassandra.retry-policy$$:: $$The retryPolicy option of WriteOptions.$$ *($$CassandraRetryPolicy$$, default: `$$<none>$$`, possible values: `DEFAULT`,`DOWNGRADING_CONSISTENCY`,`FALLTHROUGH`,`LOGGING`)*
$$cassandra.statement-expression$$:: $$The expression in Cassandra query DSL style.$$ *($$Expression$$, default: `$$<none>$$`)*
$$cassandra.ttl$$:: $$The time-to-live option of WriteOptions.$$ *($$Integer$$, default: `$$0$$`)*
//end::configuration-properties[]

//end::ref-doc[]

== Build

```
$ mvn clean package
```

== Examples

The following example assumes a JSON payload is sent to a default destination called `input`, the sink parses some of its properties (id,time,customer_id,value) and persist them into a table called `test`.

```
java -jar cassandra_sink.jar --cassandra.cluster.keyspace=test
--cassandra.ingest-query=insert into orders(id,time,customer_id, value) values (?,?,?,?)"
```

